<?php

namespace ContainerZ8ICIf1;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OBUlPyoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oBUlPyo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oBUlPyo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\Admin\\CategoriesController::add' => ['privates', '.service_locator.R2Ogf2d', 'get_ServiceLocator_R2Ogf2dService', true],
            'App\\Controller\\Admin\\CategoriesController::index' => ['privates', '.service_locator.do9sDn8', 'get_ServiceLocator_Do9sDn8Service', true],
            'App\\Controller\\Admin\\ProductsController::add' => ['privates', '.service_locator.XYfIMA2', 'get_ServiceLocator_XYfIMA2Service', true],
            'App\\Controller\\Admin\\ProductsController::delete' => ['privates', '.service_locator.cPzBaXc', 'get_ServiceLocator_CPzBaXcService', true],
            'App\\Controller\\Admin\\ProductsController::deleteImage' => ['privates', '.service_locator.CaBnCSI', 'get_ServiceLocator_CaBnCSIService', true],
            'App\\Controller\\Admin\\ProductsController::edit' => ['privates', '.service_locator.DxFgUYB', 'get_ServiceLocator_DxFgUYBService', true],
            'App\\Controller\\Admin\\ProductsController::index' => ['privates', '.service_locator.l8XAtiK', 'get_ServiceLocator_L8XAtiKService', true],
            'App\\Controller\\Admin\\UsersController::changeVerif' => ['privates', '.service_locator.Nn.tJYu', 'get_ServiceLocator_Nn_TJYuService', true],
            'App\\Controller\\Admin\\UsersController::edit' => ['privates', '.service_locator.LNn06sh', 'get_ServiceLocator_LNn06shService', true],
            'App\\Controller\\Admin\\UsersController::index' => ['privates', '.service_locator.LNn06sh', 'get_ServiceLocator_LNn06shService', true],
            'App\\Controller\\CategoriesController::list' => ['privates', '.service_locator.3M5uxVk', 'get_ServiceLocator_3M5uxVkService', true],
            'App\\Controller\\MainController::main' => ['privates', '.service_locator.do9sDn8', 'get_ServiceLocator_Do9sDn8Service', true],
            'App\\Controller\\ProductsController::details' => ['privates', '.service_locator.cPzBaXc', 'get_ServiceLocator_CPzBaXcService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.XGobEnX', 'get_ServiceLocator_XGobEnXService', true],
            'App\\Controller\\RegistrationController::resendVerif' => ['privates', '.service_locator.u85aek6', 'get_ServiceLocator_U85aek6Service', true],
            'App\\Controller\\RegistrationController::verifyUser' => ['privates', '.service_locator.2xuQBlm', 'get_ServiceLocator_2xuQBlmService', true],
            'App\\Controller\\SecurityController::forgottenPassword' => ['privates', '.service_locator.o4uQwLa', 'get_ServiceLocator_O4uQwLaService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController::resetPass' => ['privates', '.service_locator.yiOf8Hs', 'get_ServiceLocator_YiOf8HsService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin\\CategoriesController:add' => ['privates', '.service_locator.R2Ogf2d', 'get_ServiceLocator_R2Ogf2dService', true],
            'App\\Controller\\Admin\\CategoriesController:index' => ['privates', '.service_locator.do9sDn8', 'get_ServiceLocator_Do9sDn8Service', true],
            'App\\Controller\\Admin\\ProductsController:add' => ['privates', '.service_locator.XYfIMA2', 'get_ServiceLocator_XYfIMA2Service', true],
            'App\\Controller\\Admin\\ProductsController:delete' => ['privates', '.service_locator.cPzBaXc', 'get_ServiceLocator_CPzBaXcService', true],
            'App\\Controller\\Admin\\ProductsController:deleteImage' => ['privates', '.service_locator.CaBnCSI', 'get_ServiceLocator_CaBnCSIService', true],
            'App\\Controller\\Admin\\ProductsController:edit' => ['privates', '.service_locator.DxFgUYB', 'get_ServiceLocator_DxFgUYBService', true],
            'App\\Controller\\Admin\\ProductsController:index' => ['privates', '.service_locator.l8XAtiK', 'get_ServiceLocator_L8XAtiKService', true],
            'App\\Controller\\Admin\\UsersController:changeVerif' => ['privates', '.service_locator.Nn.tJYu', 'get_ServiceLocator_Nn_TJYuService', true],
            'App\\Controller\\Admin\\UsersController:edit' => ['privates', '.service_locator.LNn06sh', 'get_ServiceLocator_LNn06shService', true],
            'App\\Controller\\Admin\\UsersController:index' => ['privates', '.service_locator.LNn06sh', 'get_ServiceLocator_LNn06shService', true],
            'App\\Controller\\CategoriesController:list' => ['privates', '.service_locator.3M5uxVk', 'get_ServiceLocator_3M5uxVkService', true],
            'App\\Controller\\MainController:main' => ['privates', '.service_locator.do9sDn8', 'get_ServiceLocator_Do9sDn8Service', true],
            'App\\Controller\\ProductsController:details' => ['privates', '.service_locator.cPzBaXc', 'get_ServiceLocator_CPzBaXcService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.XGobEnX', 'get_ServiceLocator_XGobEnXService', true],
            'App\\Controller\\RegistrationController:resendVerif' => ['privates', '.service_locator.u85aek6', 'get_ServiceLocator_U85aek6Service', true],
            'App\\Controller\\RegistrationController:verifyUser' => ['privates', '.service_locator.2xuQBlm', 'get_ServiceLocator_2xuQBlmService', true],
            'App\\Controller\\SecurityController:forgottenPassword' => ['privates', '.service_locator.o4uQwLa', 'get_ServiceLocator_O4uQwLaService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController:resetPass' => ['privates', '.service_locator.yiOf8Hs', 'get_ServiceLocator_YiOf8HsService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Admin\\CategoriesController::add' => '?',
            'App\\Controller\\Admin\\CategoriesController::index' => '?',
            'App\\Controller\\Admin\\ProductsController::add' => '?',
            'App\\Controller\\Admin\\ProductsController::delete' => '?',
            'App\\Controller\\Admin\\ProductsController::deleteImage' => '?',
            'App\\Controller\\Admin\\ProductsController::edit' => '?',
            'App\\Controller\\Admin\\ProductsController::index' => '?',
            'App\\Controller\\Admin\\UsersController::changeVerif' => '?',
            'App\\Controller\\Admin\\UsersController::edit' => '?',
            'App\\Controller\\Admin\\UsersController::index' => '?',
            'App\\Controller\\CategoriesController::list' => '?',
            'App\\Controller\\MainController::main' => '?',
            'App\\Controller\\ProductsController::details' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::resendVerif' => '?',
            'App\\Controller\\RegistrationController::verifyUser' => '?',
            'App\\Controller\\SecurityController::forgottenPassword' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::resetPass' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin\\CategoriesController:add' => '?',
            'App\\Controller\\Admin\\CategoriesController:index' => '?',
            'App\\Controller\\Admin\\ProductsController:add' => '?',
            'App\\Controller\\Admin\\ProductsController:delete' => '?',
            'App\\Controller\\Admin\\ProductsController:deleteImage' => '?',
            'App\\Controller\\Admin\\ProductsController:edit' => '?',
            'App\\Controller\\Admin\\ProductsController:index' => '?',
            'App\\Controller\\Admin\\UsersController:changeVerif' => '?',
            'App\\Controller\\Admin\\UsersController:edit' => '?',
            'App\\Controller\\Admin\\UsersController:index' => '?',
            'App\\Controller\\CategoriesController:list' => '?',
            'App\\Controller\\MainController:main' => '?',
            'App\\Controller\\ProductsController:details' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:resendVerif' => '?',
            'App\\Controller\\RegistrationController:verifyUser' => '?',
            'App\\Controller\\SecurityController:forgottenPassword' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:resetPass' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
