<?php

namespace Container9QRGJHG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CategoriesController::list' => ['privates', '.service_locator.i60bMqk', 'get_ServiceLocator_I60bMqkService', true],
            'App\\Controller\\MainController::main' => ['privates', '.service_locator.do9sDn8', 'get_ServiceLocator_Do9sDn8Service', true],
            'App\\Controller\\ProductsController::details' => ['privates', '.service_locator.cPzBaXc', 'get_ServiceLocator_CPzBaXcService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.XGobEnX', 'get_ServiceLocator_XGobEnXService', true],
            'App\\Controller\\RegistrationController::resendVerif' => ['privates', '.service_locator.u85aek6', 'get_ServiceLocator_U85aek6Service', true],
            'App\\Controller\\RegistrationController::verifyUser' => ['privates', '.service_locator.2xuQBlm', 'get_ServiceLocator_2xuQBlmService', true],
            'App\\Controller\\SecurityController::forgottenPassword' => ['privates', '.service_locator.o4uQwLa', 'get_ServiceLocator_O4uQwLaService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController::resetPass' => ['privates', '.service_locator.yiOf8Hs', 'get_ServiceLocator_YiOf8HsService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CategoriesController:list' => ['privates', '.service_locator.i60bMqk', 'get_ServiceLocator_I60bMqkService', true],
            'App\\Controller\\MainController:main' => ['privates', '.service_locator.do9sDn8', 'get_ServiceLocator_Do9sDn8Service', true],
            'App\\Controller\\ProductsController:details' => ['privates', '.service_locator.cPzBaXc', 'get_ServiceLocator_CPzBaXcService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.XGobEnX', 'get_ServiceLocator_XGobEnXService', true],
            'App\\Controller\\RegistrationController:resendVerif' => ['privates', '.service_locator.u85aek6', 'get_ServiceLocator_U85aek6Service', true],
            'App\\Controller\\RegistrationController:verifyUser' => ['privates', '.service_locator.2xuQBlm', 'get_ServiceLocator_2xuQBlmService', true],
            'App\\Controller\\SecurityController:forgottenPassword' => ['privates', '.service_locator.o4uQwLa', 'get_ServiceLocator_O4uQwLaService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController:resetPass' => ['privates', '.service_locator.yiOf8Hs', 'get_ServiceLocator_YiOf8HsService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CategoriesController::list' => '?',
            'App\\Controller\\MainController::main' => '?',
            'App\\Controller\\ProductsController::details' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::resendVerif' => '?',
            'App\\Controller\\RegistrationController::verifyUser' => '?',
            'App\\Controller\\SecurityController::forgottenPassword' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::resetPass' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CategoriesController:list' => '?',
            'App\\Controller\\MainController:main' => '?',
            'App\\Controller\\ProductsController:details' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:resendVerif' => '?',
            'App\\Controller\\RegistrationController:verifyUser' => '?',
            'App\\Controller\\SecurityController:forgottenPassword' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:resetPass' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]));
    }
}
