<?php

namespace Container9QRGJHG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCouponsTypesRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CouponsTypesRepository' shared autowired service.
     *
     * @return \App\Repository\CouponsTypesRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CouponsTypesRepository'] = new \App\Repository\CouponsTypesRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
