<?php

namespace Container9QRGJHG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrdersRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\OrdersRepository' shared autowired service.
     *
     * @return \App\Repository\OrdersRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\OrdersRepository'] = new \App\Repository\OrdersRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
