<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9QRGJHG\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9QRGJHG/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container9QRGJHG.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container9QRGJHG\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container9QRGJHG\App_KernelProdContainer([
    'container.build_hash' => '9QRGJHG',
    'container.build_id' => 'c3aad1d4',
    'container.build_time' => 1705857853,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container9QRGJHG');
