<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'categories_list' => [['slug'], ['_controller' => 'App\\Controller\\CategoriesController::list'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/categories']], [], [], []],
    'app_main' => [[], ['_controller' => 'App\\Controller\\MainController::main'], [], [['text', '/']], [], [], []],
    'products_index' => [[], ['_controller' => 'App\\Controller\\ProductsController::index'], [], [['text', '/produits/']], [], [], []],
    'products_details' => [['slug'], ['_controller' => 'App\\Controller\\ProductsController::details'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/produits']], [], [], []],
    'profile_index' => [[], ['_controller' => 'App\\Controller\\ProfileController::index'], [], [['text', '/profil/']], [], [], []],
    'profile_orders' => [[], ['_controller' => 'App\\Controller\\ProfileController::orders'], [], [['text', '/profil/commandes']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/inscription']], [], [], []],
    'verify_user' => [['token'], ['_controller' => 'App\\Controller\\RegistrationController::verifyUser'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/verif']], [], [], []],
    'resend_verif' => [[], ['_controller' => 'App\\Controller\\RegistrationController::resendVerif'], [], [['text', '/renvoiverif']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/connexion']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/deconnexion']], [], [], []],
    'forgotten_password' => [[], ['_controller' => 'App\\Controller\\SecurityController::forgottenPassword'], [], [['text', '/oubli-pass']], [], [], []],
    'reset_pass' => [['token'], ['_controller' => 'App\\Controller\\SecurityController::resetPass'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/oubli-pass']], [], [], []],
    'App\Controller\CategoriesController::list' => [['slug'], ['_controller' => 'App\\Controller\\CategoriesController::list'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/categories']], [], [], []],
    'App\Controller\MainController::main' => [[], ['_controller' => 'App\\Controller\\MainController::main'], [], [['text', '/']], [], [], []],
    'App\Controller\ProductsController::index' => [[], ['_controller' => 'App\\Controller\\ProductsController::index'], [], [['text', '/produits/']], [], [], []],
    'App\Controller\ProductsController::details' => [['slug'], ['_controller' => 'App\\Controller\\ProductsController::details'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/produits']], [], [], []],
    'App\Controller\ProfileController::index' => [[], ['_controller' => 'App\\Controller\\ProfileController::index'], [], [['text', '/profil/']], [], [], []],
    'App\Controller\ProfileController::orders' => [[], ['_controller' => 'App\\Controller\\ProfileController::orders'], [], [['text', '/profil/commandes']], [], [], []],
    'App\Controller\RegistrationController::register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/inscription']], [], [], []],
    'App\Controller\RegistrationController::verifyUser' => [['token'], ['_controller' => 'App\\Controller\\RegistrationController::verifyUser'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/verif']], [], [], []],
    'App\Controller\RegistrationController::resendVerif' => [[], ['_controller' => 'App\\Controller\\RegistrationController::resendVerif'], [], [['text', '/renvoiverif']], [], [], []],
    'App\Controller\SecurityController::login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/connexion']], [], [], []],
    'App\Controller\SecurityController::logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/deconnexion']], [], [], []],
    'App\Controller\SecurityController::forgottenPassword' => [[], ['_controller' => 'App\\Controller\\SecurityController::forgottenPassword'], [], [['text', '/oubli-pass']], [], [], []],
    'App\Controller\SecurityController::resetPass' => [['token'], ['_controller' => 'App\\Controller\\SecurityController::resetPass'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/oubli-pass']], [], [], []],
];
