<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Categories extends \App\Entity\Categories implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categories' => [parent::class, 'categories', null],
        "\0".parent::class."\0".'categoryOrder' => [parent::class, 'categoryOrder', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'parent' => [parent::class, 'parent', null],
        "\0".parent::class."\0".'products' => [parent::class, 'products', null],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null],
        'categories' => [parent::class, 'categories', null],
        'categoryOrder' => [parent::class, 'categoryOrder', null],
        'id' => [parent::class, 'id', null],
        'name' => [parent::class, 'name', null],
        'parent' => [parent::class, 'parent', null],
        'products' => [parent::class, 'products', null],
        'slug' => [parent::class, 'slug', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
