<?php

namespace ContainerYeNE5sZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CaBnCSIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CaBnCSI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CaBnCSI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'image' => ['privates', '.errored..service_locator.CaBnCSI.App\\Entity\\Images', NULL, 'Cannot autowire service ".service_locator.CaBnCSI": it needs an instance of "App\\Entity\\Images" but this type has been excluded in "config/services.yaml".'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'pictureService' => ['privates', 'App\\Service\\PictureService', 'getPictureServiceService', true],
        ], [
            'image' => 'App\\Entity\\Images',
            'manager' => '?',
            'pictureService' => 'App\\Service\\PictureService',
        ]);
    }
}
