<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ8ICIf1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ8ICIf1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ8ICIf1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ8ICIf1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ8ICIf1\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z8ICIf1',
    'container.build_id' => 'b6e397e8',
    'container.build_time' => 1706378691,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ8ICIf1');
