<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH2NJw1p\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH2NJw1p/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH2NJw1p.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH2NJw1p\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH2NJw1p\App_KernelDevDebugContainer([
    'container.build_hash' => 'H2NJw1p',
    'container.build_id' => '0963f8fe',
    'container.build_time' => 1706693790,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH2NJw1p');
