<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Orders extends \App\Entity\Orders implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'coupons' => [parent::class, 'coupons', null],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'ordersDetails' => [parent::class, 'ordersDetails', null],
        "\0".parent::class."\0".'reference' => [parent::class, 'reference', null],
        "\0".parent::class."\0".'users' => [parent::class, 'users', null],
        'coupons' => [parent::class, 'coupons', null],
        'created_at' => [parent::class, 'created_at', null],
        'id' => [parent::class, 'id', null],
        'ordersDetails' => [parent::class, 'ordersDetails', null],
        'reference' => [parent::class, 'reference', null],
        'users' => [parent::class, 'users', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
