<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Coupons extends \App\Entity\Coupons implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'code' => [parent::class, 'code', null],
        "\0".parent::class."\0".'coupons_types' => [parent::class, 'coupons_types', null],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'discount' => [parent::class, 'discount', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'is_valid' => [parent::class, 'is_valid', null],
        "\0".parent::class."\0".'max_usage' => [parent::class, 'max_usage', null],
        "\0".parent::class."\0".'orders' => [parent::class, 'orders', null],
        "\0".parent::class."\0".'validity' => [parent::class, 'validity', null],
        'code' => [parent::class, 'code', null],
        'coupons_types' => [parent::class, 'coupons_types', null],
        'created_at' => [parent::class, 'created_at', null],
        'description' => [parent::class, 'description', null],
        'discount' => [parent::class, 'discount', null],
        'id' => [parent::class, 'id', null],
        'is_valid' => [parent::class, 'is_valid', null],
        'max_usage' => [parent::class, 'max_usage', null],
        'orders' => [parent::class, 'orders', null],
        'validity' => [parent::class, 'validity', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
